### ISSUE TITLE
[GSoC] Testing Framework: Compliance Suite and Tool for Disabling Problematic Tests

### ISSUE THREAD

**Issue by ArrangingErmine** [pybee/ouroboros#16]
# **Table of Content**

1.  **Intro:**  1.1 Intro, 1.2 Goals, 1.3 Benefits
2.  **Schedule and Process**
3.  **Risk Analysis**

# **1. Intro:**

For my GSoC 2018 project I would like to contribute to Ouroboros by resolving the issues it's been having with Pythons test suite. Ouroboros is currently unable to run CPython’s test suite and therefore is allowing many unknown issues to arise. A number of problems also currently occur when running tests on certain operating systems (e.g IOS and Android).

## 1.2 Goals:

- The ability to test  the compliance of the Ouroboros library.

- Full platform support for IOS

- A list of features that must be implemented in order for the Ouroboros library to be compliant with a standard Python installation.

- A list of tests that cause errors to arise on certain platforms and a tool to disable the tests that are flagged for the platform on which it is running.

- Port some pure Python implementations from other repositories

- Integrate updated library into batavia

## 1.3 Benefits

Testing support across platforms will help the PyBee project’s goal of a unified codebase. VOC and Bratavia users have been reporting issues regarding this problem so other PyBee projects will benefit from this fix. Gathering a list of features that must be implemented in order to make Ouroboros feature complete would give contributors a solid roadmap and encourage developers to undertake some of the smaller tasks.


# **2. Schedule and Process**

## Week 1
I will designate the first week to doing a preliminary analysis. During this week I will compile a list of reported errors related to the ouroboros, run small tests using the library over IOS and Batavia, and get comfortable testing across a variety of emulated platforms.

**Week 1:** Setup development environments on every platform. 

**Goals**

- [ ] Becoming comfortable with variety of testing tools and environments.
- [ ] Ensuring I have the appropriate environment setup to maximize the efficiency of the project.

## Week 2 - 4
Currently, Ouroboros is lacking a complete implementation of CPython’s `test` package. 

Over weeks 2,3 and 4 I will begin extensive analysis of which Ouroboros features will need to be implemented so we can get the library to a point where it can run every one of these tests. This task may be a long process given the size of Python's library. I will import the full CPython test suite and run it to make a comprehensive list of errors.

**Week 2:** Import Cpython test package. Import `run_tests.py`. I will need disable some of the regression tests that call non primitive CPython elements and other functions that are not supported. I will create a function to quickly re-enable these tests once a contribution has been made. This may take up to a week.
I have created a list of regression tests that are yet to be integrated into the Ouroboros test package: https://docs.google.com/document/d/1BBSfDbnIHp0eGL1FSz5GL4p7UBSocQTidN4EDZMDaiU/edit?usp=sharing
**Week 3+4:** I will clearly document every external dependency the library currently has. Hopefully through this, it will give a baseline to reference for any future users of the library. This may take up to two weeks.
With the independent elements, I will test their coverage within the CPython library and use that information to create list of needed implementations in order of priority. 

**Goals**

- [ ] Import `cpython/Lib/test/` in its entirety.
- [ ] Import `cpython/Tools/scripts/run_tests.py`
- [ ] Modify CPython’s test suite to get it running with Ouroboros in its current state.

## Week 5-8
From week 5 to 8, I will create modify `run_tests.py` so that it can read a list of known platform specific errors that are specified in a config file. I will add in a line that identifies the operating system and then modify the script to skip the tests specific to that platform.

Once this tool is created I will continue to expand the list of known errors by executing trial and error tests.

**Week 5:** Create mechanism for disabling tests. Add known failures to config file. Research any reported errors from PyBee and outside projects that outline errors related to the platform on which it is running. Document failures.
**Week 6+7:** Run trial and error tests on IOS i.e Run test suite and compile list of android specific failures. Use most recent version of Android. Once list is completed, perform repeat these tests on earlier versions.
**Week 8:** Repeat this process on Android.

**Goals**

- [ ]  Modify `run_tests.py` to get it working with Ouroboros.
- [ ]  Expand list of known platform specific errors on IOS and Android

## Week 9-12
By this stage I will have a list of needed CPython implementations and will be able to mark the priority of each needed implementation. For week 7  I will audit PyPy for pure python implementations and look for any other projects from which I can import code without encountering license issues. I wrote a python tool for checking matching filenames in github repositories so this may come in useful for this stage of the project. For the final week I will integrate the updated Ouroboros library into Batavia. This will require enabling some of the regression tests that were previously disabled and running `run_tests.py` in order to check the library's compliance with a normal installation of CPython.

Reference: https://bitbucket.org/pypy/pypy/src/f65cb735be28/lib_pypy/?at=default

**Week 9+10:** Analyse other repositories (e.g PyPy) to create list of valuable files they have that we could port over to Ouroboros. Import these files over and ensure they are fully functional within Ouroboros. 
**Week 11:** Enabling the tests from `test` that were previously disabled due to their absence in this project and re-testing on other platforms.
**Week 12:** Integrate updated library into Batavia.

**Goals**

- [ ] Expand the Ouroboros library by importing code from outside sources.
- [ ] Enable Batavia support for updated library

# 3. Risk Analysis
**---Note---**
Having not yet completed my module in Software Testing at university, I am aware that there may be some risks that I may not yet be aware of. However, I will have completed this module by the time GSoC starts and I also intend on independently studying this area thoroughly to prepare for this project. Given that I will be committing 45-50+ hours a week to this I am quite confident that I will have a good chance of overcoming any problems that I run into.
**----------**

- Importing the CPython test suite is sure to cause a huge number of errors. A preliminary analysis will give me of good idea of where to start when undertaking this task.

- Depending on the number of OS specific errors that arise, the test disabling tool could prove to be a relatively slow program. It may take time to optimize this feature.

- Changes to the CPython code could result in side effects that take time to correct. When it comes to this stage, a test driven development will be important to maintain efficiency.

- Finding failures through trial and error is quite a general task. It will be important to set requirements for myself at this stage to keep on schedule.

- Importing from outside libraries may cause unforeseen errors. It will be important to review the documentation on the repositories from which I am taking, check licenses, and look at any related issues that have been reported.

**Comment by freakboy3742** [comment]
@ArrangingErmine Your schedule needs a *lot* more detail. When we said a "week-by-week schedule", we mean *week-by-week*, not month-by-month. We're looking for very fine detail of what you're planning to work on, and how long you'll think it will take. Those estimates almost certainly won't be accurate - but you won't be able to produce a detailed estimate unless you understand the problem you're trying to solve, and *that* is what we're looking for.

**Comment by ArrangingErmine** [comment]
@freakboy3742 I updated the draft with a further breakdown of what I will be doing each week. I also added an item for importing code from other repositories.

Are there any elements you think I should expand on further or is it all still too vague? 
And does this seem like a realistic timescale?

Thank you

**Comment by freakboy3742** [comment]
@ArrangingErmine I think I've miscommunicated some of the requirements here. 

The approach you've described in Week 5 is something the CPython test suite already has; but it's not a feature we can use. We need to do this in a way that has minimal impact on the CPython source themselves. We need to be able to *externally* maintain the list of tests that can't/won't run as part of the project, and have the run_tests script honor that list. We can possibly get a minimal change into run_tests.py to support external configuration, but we're not going to be able to annotate every method in the standard library test suite with details of platforms where that method doesn't work.

Relying on anything in Batavia and VOC is also going to be risky - the standard library in those projects is *really* minimal, so your plan in weeks 2-4 will almost certainly blow out because there simply isn't enough currently working in the standard library. If this proposal was to mostly ignore VOC and Batavia, and focus on getting iOS platform testing working, that would be plenty. Batavia/VOC integration would be best as an "at the end, if we get time" focus, rather than the core focus of the project; and it would probably be best to focus on *one* of them, rather than trying to do *both*.

Weeks 11 and 12 are also still too vague - "I'll pick something and do it". How do you know what you'll pick will fit in the available time?

**Comment by ArrangingErmine** [comment]
Hey @freakboy3742 

Yes, that approach makes much more sense. I've edited that section to make the goal of that week to modify `run_tests.py` instead of a tool that makes changes to the source.

I've also changed the proposal to focus more on IOS platform testing. I added a week to that period (6+7) and I took out Batavia and Voc testing from the first couple of weeks.

For the final two weeks I had previously allocated time to converting two CPython modules into Python.
Since I added a week of time to IOS platform testing I had one week remaining. For this week I could integrate the updated library into Batavia.

I also left in a week for android platform testing. Do you think that would be worthwhile or do you think it would be better to exclusively work with IOS?

What do you think of these changes?

**Comment by freakboy3742** [comment]
@ArrangingErmine This is getting better. A couple of "2 week" tasks have slipped back in, though; and there's a couple of tasks that seem a bit "wooly" ("up to two weeks" to document dependencies; 2 weeks to run the test suite on iOS, but only 1 week for Android). If a schedule feels padded to a reviewer, that's a problem. It might be padded because there are details and complications that you haven't described... but it might be because you don't understand the problem - or worse, that it's actually padded.

Android testing is essentially the same as VOC testing - it would end up being a test of the standard library that ships with VOC, but with a slightly different set of "system" libraries. The context in which included it makes sense; although it might be easier to just test VOC specifically, rather than get Android involved (due to the complication of actually running code on Android).

**Comment by ArrangingErmine** [comment]
Thanks @freakboy3742 

I don't have much experience with developing on IOS so  I'm a little unsure as to how long that process would take. My feeling was that it would just consistently run into errors and would  be quite a repetitive process. I also thought that because I would be setting out focused on IOS I would get testing to run on that platform and perhaps just get a small start on another platform. I see your point though, I'll change that right away.

I just want to clarify, are you saying that I am allocating way too much time to get the test suite running on IOS or do you think I should spend two weeks getting it to work and then spend the two weeks after that getting it to work on VOC?

**Comment by freakboy3742** [comment]
Closing on the basis that this GSoC project was unsuccessful, and we're not participating in GSoC any more.
