### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by vovanz** [pybee/ouroboros#18]
Is this project alive? The fact that the last commit was more than a year ago doesn't look very good...

**Comment by freakboy3742** [comment]
Ouroboros is part of a bigger picture, so you have to view it in that light. Ouroboros hasn't had a commit in a year; but the related projects (VOC, Batavia) are in active development. Essentially, there isn't much point working actively on Ouroboros until the language implementations work. 

That said - if you *want* to contribute to Ouroboros, you would be welcome to do so :-)
