### ISSUE TITLE
Logo is misleading

### ISSUE THREAD

**Issue by Xjs** [pybee/ouroboros#19]
I would expect something like https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Serpiente_alquimica.jpg/220px-Serpiente_alquimica.jpg, not a giant bumble bee (which is also very cute tho).

**Comment by freakboy3742** [comment]
Thanks - Ouroboros is part of the BeeWare Project - hence the logo. We haven't got around to developing a BeeWare-styled serpent logo, but it's on our todo list.
