### ISSUE TITLE
No PyPI releases

### ISSUE THREAD

**Issue by jayvdb** [pybee/ouroboros#22]
https://pypi.org/simple/ouroboros/ is empty

**Comment by freakboy3742** [comment]
Yes - because we haven't made any releases yet. 

There's also a question as to what a release would mean; Ouroboros itself isn't a useful product, it's something you need in the context of a separate Python interpreter.

**Comment by jayvdb** [comment]
I guess I'll just have to use master then, and report issues against shas.
