### ISSUE TITLE
Wrong documentation link?

### ISSUE THREAD

**Issue by lurch** [pybee/ouroboros#3]
If I follow the link that README.rst gives for the [documentation](http://ouroboros.readthedocs.org/) it says 

> Ouroboros is a simple wrapper for the eventstore management APIs, designed for managing permissions on streams. It is not a fully-featured eventstore client.

which sounds like something **very** different to the "A standalone, pure Python implementation of the Python Standard Library." that README.rst describes.

**Comment by freakboy3742** [comment]
Hrm. Looks like we've got a namespace clash. Need to register a different project name on RTD.
