### ISSUE TITLE
What's the audio library for BeeWare / What kind of latency is there with audio.py?

### ISSUE THREAD

**Issue by mavavilj** [pybee/ouroboros#31]
What kind of latency is there with audio.py (https://github.com/beeware/ouroboros/blob/master/ouroboros/email/mime/audio.py)?

How does this compare or relate to:

https://developer.android.com/ndk/guides/audio/aaudio/aaudio

**Comment by freakboy3742** [comment]
I'm not really sure what question you're asking here. The package you've tagged is an email mime library. It doesn't have "latency" - it's a class for representing `audio/*` MIMEtypes. So... it doesn't compare to NDK audio libraries at all.

**Comment by mavavilj** [comment]
Oops, this comes up as first, when writing "beeware audio" to a web search.

So what's meant to be used for (Android) audio in BeeWare?

**Comment by freakboy3742** [comment]
At the moment, nothing - we don't provide a cross platform audio API.
